"""baseline schema

Revision ID: fc0ecac68804
Revises:
Create Date: 2026-09-23 11:53:49.386552

ADIM (Database Migration Strategy) - bu migration, mevcut `app.db.
init_db()`'nin `Base.metadata.create_all()` ile kurduğu 12 tabloluk
şemanın (Madde 1 + queue + health - autogenerate ile, gerçek bir MySQL
8'e karşı, TAMAMEN BOŞ bir DB'de üretildi) BASELINE'ıdır.

İki farklı senaryo için İKİ farklı komut:

  FRESH DB (hiç tablo yok):
      alembic upgrade head
      -> bu migration GERÇEKTEN çalışır, 12 tabloyu CREATE TABLE ile
         kurar (create_all()'ın yaptığının BİREBİR aynısı, ama artık
         Alembic'in versiyon geçmişinde İZLENEBİLİR).

  MEVCUT DB (tablolar zaten create_all() ile kurulmuş, prod dahil):
      alembic stamp head
      -> hiçbir CREATE TABLE ÇALIŞTIRMAZ, SADECE alembic_version
         tablosuna "bu DB zaten bu revizyonda" der - mevcut şemaya
         DOKUNMADAN Alembic'in geçmişine dahil eder. Bu DB'de create_
         all() ZATEN çalışmış olduğu için `upgrade head` burada YANLIŞ
         olurdu (CREATE TABLE IF NOT EXISTS semantiği yok, gerçek
         MySQL'de var olan tabloyu tekrar yaratmaya çalışmak hataya
         yol açar).

Bu ayrım (fresh->upgrade, existing->stamp) production deploy
adımlarının KENDİSİ - bu dosyanın içinde KODLANMAZ, deploy
dokümantasyonunda (README/deploy/systemd) açıklanır.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0ecac68804'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_capacity',
    sa.Column('icao_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('recalculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('icao_code')
    )
    op.create_table('aircraft_capacity_family',
    sa.Column('icao_prefix', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('default_capacity', sa.Integer(), nullable=False),
    sa.Column('counts_toward_passenger_total', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('icao_prefix')
    )
    op.create_table('airline_fleet_seat_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('icao_code', sa.String(length=8), nullable=False),
    sa.Column('airline_iata', sa.String(length=3), nullable=True),
    sa.Column('airline_name', sa.String(length=128), nullable=True),
    sa.Column('variant_name', sa.String(length=64), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('fleet_count', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.String(length=16), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_afsc_icao_airline', 'airline_fleet_seat_config', ['icao_code', 'airline_iata'], unique=False)
    op.create_index(op.f('ix_airline_fleet_seat_config_airline_iata'), 'airline_fleet_seat_config', ['airline_iata'], unique=False)
    op.create_index(op.f('ix_airline_fleet_seat_config_icao_code'), 'airline_fleet_seat_config', ['icao_code'], unique=False)
    op.create_table('airport_operational_configs',
    sa.Column('airport_iata', sa.String(length=10), nullable=False),
    sa.Column('passport_counter_count', sa.Integer(), nullable=False),
    sa.Column('passport_staff_count', sa.Integer(), nullable=False),
    sa.Column('passport_service_time_minutes', sa.Float(), nullable=False),
    sa.Column('security_lane_count', sa.Integer(), nullable=False),
    sa.Column('domestic_security_lane_count', sa.Integer(), nullable=False),
    sa.Column('international_security_lane_count', sa.Integer(), nullable=False),
    sa.Column('security_service_time_minutes', sa.Float(), nullable=False),
    sa.Column('passport_staff_per_counter', sa.Float(), nullable=False),
    sa.Column('passport_service_rate_per_staff', sa.Float(), nullable=False),
    sa.Column('passport_efficiency_multiplier', sa.Float(), nullable=False),
    sa.Column('passport_departure_server_count', sa.Integer(), nullable=True),
    sa.Column('passport_arrival_server_count', sa.Integer(), nullable=True),
    sa.Column('arrival_bank_threshold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('airport_iata')
    )
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=10), nullable=False),
    sa.Column('icao_code', sa.String(length=10), nullable=True),
    sa.Column('airport_name', sa.String(length=500), nullable=True),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=4), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('scale', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_index(op.f('ix_airports_country_code'), 'airports', ['country_code'], unique=False)
    op.create_table('baseline_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airport_iata', sa.String(length=10), nullable=False),
    sa.Column('process', sa.String(length=16), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_iata', 'process', 'window_start', name='uq_baseline_observation_window')
    )
    op.create_index(op.f('ix_baseline_observations_airport_iata'), 'baseline_observations', ['airport_iata'], unique=False)
    op.create_index(op.f('ix_baseline_observations_window_start'), 'baseline_observations', ['window_start'], unique=False)
    op.create_table('flight_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_key', sa.String(length=64), nullable=False),
    sa.Column('airport_iata', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.String(length=64), nullable=True),
    sa.Column('new_value', sa.String(length=64), nullable=True),
    sa.Column('flight_effective_time', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_events_airport_iata'), 'flight_events', ['airport_iata'], unique=False)
    op.create_index(op.f('ix_flight_events_flight_effective_time'), 'flight_events', ['flight_effective_time'], unique=False)
    op.create_index(op.f('ix_flight_events_flight_key'), 'flight_events', ['flight_key'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_key', sa.String(length=64), nullable=False),
    sa.Column('airport_iata', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('airline_iata', sa.String(length=8), nullable=True),
    sa.Column('flight_number', sa.String(length=16), nullable=True),
    sa.Column('flight_iata', sa.String(length=16), nullable=True),
    sa.Column('aircraft_icao', sa.String(length=8), nullable=True),
    sa.Column('aircraft_match_found', sa.Boolean(), nullable=False),
    sa.Column('dep_iata', sa.String(length=10), nullable=True),
    sa.Column('arr_iata', sa.String(length=10), nullable=True),
    sa.Column('dep_scheduled_utc', sa.DateTime(), nullable=True),
    sa.Column('dep_estimated_utc', sa.DateTime(), nullable=True),
    sa.Column('dep_actual_utc', sa.DateTime(), nullable=True),
    sa.Column('arr_scheduled_utc', sa.DateTime(), nullable=True),
    sa.Column('arr_estimated_utc', sa.DateTime(), nullable=True),
    sa.Column('arr_actual_utc', sa.DateTime(), nullable=True),
    sa.Column('dep_terminal', sa.String(length=16), nullable=True),
    sa.Column('dep_gate', sa.String(length=16), nullable=True),
    sa.Column('arr_terminal', sa.String(length=16), nullable=True),
    sa.Column('arr_gate', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_airport_iata'), 'flights', ['airport_iata'], unique=False)
    op.create_index(op.f('ix_flights_flight_iata'), 'flights', ['flight_iata'], unique=False)
    op.create_index(op.f('ix_flights_flight_key'), 'flights', ['flight_key'], unique=True)
    op.create_table('historical_flight_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airport_iata', sa.String(length=10), nullable=False),
    sa.Column('process', sa.String(length=16), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('average_flight_count', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('average_expected_passengers', sa.Float(), nullable=True),
    sa.Column('passenger_sample_size', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_iata', 'process', 'hour_of_day', 'day_of_week', name='uq_historical_flight_count')
    )
    op.create_index(op.f('ix_historical_flight_counts_airport_iata'), 'historical_flight_counts', ['airport_iata'], unique=False)
    op.create_table('queue_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airport_iata', sa.String(length=10), nullable=False),
    sa.Column('process', sa.String(length=16), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('operational_date', sa.Date(), nullable=True),
    sa.Column('flight_count', sa.Integer(), nullable=False),
    sa.Column('expected_passengers', sa.Integer(), nullable=False),
    sa.Column('baseline_ratio', sa.Float(), nullable=True),
    sa.Column('flight_ratio', sa.Float(), nullable=True),
    sa.Column('passenger_ratio', sa.Float(), nullable=True),
    sa.Column('utilization', sa.Float(), nullable=True),
    sa.Column('estimated_wait_minutes', sa.Float(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_iata', 'process', 'window_start', name='uq_queue_prediction_window')
    )
    op.create_index(op.f('ix_queue_predictions_airport_iata'), 'queue_predictions', ['airport_iata'], unique=False)
    op.create_index(op.f('ix_queue_predictions_operational_date'), 'queue_predictions', ['operational_date'], unique=False)
    op.create_index(op.f('ix_queue_predictions_window_start'), 'queue_predictions', ['window_start'], unique=False)
    op.create_table('unknown_aircraft_types',
    sa.Column('icao_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('icao_code')
    )
    op.create_table('worker_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_successful_refresh_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_status')
    op.drop_table('unknown_aircraft_types')
    op.drop_index(op.f('ix_queue_predictions_window_start'), table_name='queue_predictions')
    op.drop_index(op.f('ix_queue_predictions_operational_date'), table_name='queue_predictions')
    op.drop_index(op.f('ix_queue_predictions_airport_iata'), table_name='queue_predictions')
    op.drop_table('queue_predictions')
    op.drop_index(op.f('ix_historical_flight_counts_airport_iata'), table_name='historical_flight_counts')
    op.drop_table('historical_flight_counts')
    op.drop_index(op.f('ix_flights_flight_key'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_iata'), table_name='flights')
    op.drop_index(op.f('ix_flights_airport_iata'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_flight_events_flight_key'), table_name='flight_events')
    op.drop_index(op.f('ix_flight_events_flight_effective_time'), table_name='flight_events')
    op.drop_index(op.f('ix_flight_events_airport_iata'), table_name='flight_events')
    op.drop_table('flight_events')
    op.drop_index(op.f('ix_baseline_observations_window_start'), table_name='baseline_observations')
    op.drop_index(op.f('ix_baseline_observations_airport_iata'), table_name='baseline_observations')
    op.drop_table('baseline_observations')
    op.drop_index(op.f('ix_airports_country_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_table('airport_operational_configs')
    op.drop_index(op.f('ix_airline_fleet_seat_config_icao_code'), table_name='airline_fleet_seat_config')
    op.drop_index(op.f('ix_airline_fleet_seat_config_airline_iata'), table_name='airline_fleet_seat_config')
    op.drop_index('idx_afsc_icao_airline', table_name='airline_fleet_seat_config')
    op.drop_table('airline_fleet_seat_config')
    op.drop_table('aircraft_capacity_family')
    op.drop_table('aircraft_capacity')
    # ### end Alembic commands ###
